### ISSUE TITLE
Router#options is missing?

### ISSUE THREAD

**Issue by azu** [gzuidhof/sunder#1]
[tiny-request-router](https://github.com/berstend/tiny-request-router) has [.options(path, handler, options)](https://github.com/berstend/tiny-request-router#optionspath-handler-options), but sunder does not expose `options` method in `Router`.

Is this intended?

**Comment by gzuidhof** [comment]
Oops, no this is not intended! I can merge the fix for it tomorrow, or I'm happy to accept a PR :)

**Comment by gzuidhof** [comment]
Fixed in 0.7.1, thank you!

**Comment by azu** [comment]
Thanks!
